### Site Settings ###
title               : CocoaSounds
description         : >-
                      Breaking new ground in the world of sound.
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : CocoaBeanzz/CocoaBeanzz.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : true                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji
  - jekyll-readme-index


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md

### Use README.md as index.md
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: true


### Author Info ###
author:
  name              : K Preston
  image             : https://github.com/CocoaBeanzz/CocoaSounds/blob/main/_media/me_painting_5_12_23_SMALL.png?raw=true
# behance           : your_username
# dribbble          : your_username
  email             : k.preston@digipen.edu
# facebook          : your_username
  github            : CocoaBeanzz
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : kl-preston
# medium            : your_username
  soundcloud        : CocoaBeanz
  spotify           : 6YVhlNw952WlFsXddTPgOY
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
  youtube           : KPresto
# keybase           : your_username
  itch.io           : CocoaBeanz


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
#disqus:
#  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
#buymeacoffee:
#  enabled: false
#  username: your_username
#  color: "#007bff"
#  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
#  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - ".vs"